name: super_string
description: Some of the most common and useful string methods, Inspired by various other programming languages.
version: 1.0.2
homepage: https://github.com/Anas35/super_string

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.16.5